import numpy as np
import math



pi = math.pi
r = 0.08 #m 

# The fucntion takes input of a desired force/torque fx, fy, tau with the orientation
# of the robot defined in the inertial frame with the angle alpha
# and output the force required to be generated by the three thrusters.

def force_decomp(fx,fy,tau,alpha):

#    print(alpha)
    m11 = math.cos(2*pi/3+alpha)
    
    m12 = math.cos(pi/3+alpha)
    
    m13 = math.cos(alpha)
    
    m21 = math.sin(2*pi/3+alpha)
    
    m22 = math.sin(pi/3+alpha)
    
    m23 = math.sin(alpha)
    
    matrix1 = np.matrix([[m11,m12,m13],[m21,m22,m23],[r,-r,r]])
   
#    print(matrix1)  
    mat1inv = matrix1.I

    matrix2 = np.matrix([[fx],[fy],[tau]])

    decomp = matrix1*matrix2
#    print(matrix2)
    return decomp

#test case
#a = force_decomp(1,1,1,pi)

#print(a)
    
